#############################################################################
# Makefile for building: pi_controller
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  pi_controller.pro
# Template: app
# Command: /home/dandi/raspi/qt5/bin/qmake -o Makefile pi_controller.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/dandi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc
CXX           = /home/dandi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/dandi/raspi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/dandi/raspi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../raspi/qt5pi/include -I../raspi/qt5pi/include/QtCharts -I../raspi/qt5pi/include/QtWidgets -I../raspi/qt5pi/include/QtGui -I../raspi/qt5pi/include/QtCore -I. -I=/opt/vc/include -I=/opt/vc/include/interface/vcos/pthreads -I=/opt/vc/include/interface/vmcs_host/linux -I../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++
QMAKE         = /home/dandi/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/dandi/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/dandi/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pi_controller1.0.0
DISTDIR = /home/dandi/pi_controller/.tmp/pi_controller1.0.0
LINK          = /home/dandi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/dandi/raspi/sysroot -Wl,-O1 -Wl,-rpath-link,/home/dandi/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/dandi/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/dandi/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L=/opt/vc/lib -lpigpio -L/home/dandi/raspi/qt5pi/plugins/platforms -lqeglfs -L/home/dandi/raspi/qt5pi/lib -L/home/dandi/raspi/sysroot/usr/lib/arm-linux-gnueabihf -L/home/dandi/raspi/sysroot/lib/arm-linux-gnueabihf -L/home/dandi/raspi/qt5pi/plugins/imageformats -lqgif -lqico -lqjpeg -ljpeg -L/home/dandi/raspi/qt5pi/plugins/egldeviceintegrations -lqeglfs-brcm-integration -lbcm_host -lqeglfs-emu-integration -lqeglfs-kms-integration -lQt5EglFsKmsSupport -lQt5EglFSDeviceIntegration -lQt5EventDispatcherSupport -lQt5ServiceSupport -lQt5ThemeSupport -lQt5DBus -ldbus-1 -lQt5FontDatabaseSupport -lfontconfig -lfreetype -lQt5FbSupport -lQt5EglSupport -lXext -lX11 -lQt5InputSupport -lmtdev -linput -lxkbcommon -lQt5PlatformCompositorSupport -lQt5KmsSupport -lQt5DeviceDiscoverySupport -ludev -lQt5EdidSupport -lgbm -ldrm -lts -lEGL -lQt5Charts -lQt5Widgets -lQt5Gui -lpng16 -lharfbuzz -lQt5Core -lm -lz -lqtpcre2 -ldouble-conversion -ldl -lgthread-2.0 -lglib-2.0 -lGLESv2 -lpthread 
AR            = /home/dandi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/dandi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		chart.cpp \
		rootwidget.cpp \
		sequence.cpp \
		ds18b20.cpp /home/dandi/pi_controller/pi_controller_plugin_import.cpp \
		moc_chart.cpp \
		moc_rootwidget.cpp \
		moc_ds18b20.cpp
OBJECTS       = main.o \
		chart.o \
		rootwidget.o \
		sequence.o \
		ds18b20.o \
		pi_controller_plugin_import.o \
		moc_chart.o \
		moc_rootwidget.o \
		moc_ds18b20.o
DIST          = ../raspi/qt5/mkspecs/features/spec_pre.prf \
		../raspi/qt5/mkspecs/common/unix.conf \
		../raspi/qt5/mkspecs/common/linux.conf \
		../raspi/qt5/mkspecs/common/sanitize.conf \
		../raspi/qt5/mkspecs/common/gcc-base.conf \
		../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../raspi/qt5/mkspecs/common/g++-base.conf \
		../raspi/qt5/mkspecs/common/g++-unix.conf \
		../raspi/qt5/mkspecs/qdevice.pri \
		../raspi/qt5/mkspecs/features/device_config.prf \
		../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../raspi/qt5/mkspecs/qconfig.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_cupsprintersupport.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-brcm-integration.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-emu-integration.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-kms-integration.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qlibinputplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qminimalegl.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlite2.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qtslibplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qvnc.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qxcb.pri \
		../raspi/qt5/mkspecs/features/qt_functions.prf \
		../raspi/qt5/mkspecs/features/qt_config.prf \
		../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../raspi/qt5/mkspecs/features/toolchain.prf \
		../raspi/qt5/mkspecs/features/default_pre.prf \
		../raspi/qt5/mkspecs/features/resolve_config.prf \
		../raspi/qt5/mkspecs/features/default_post.prf \
		../raspi/qt5/mkspecs/features/warn_on.prf \
		../raspi/qt5/mkspecs/features/qt.prf \
		../raspi/qt5/mkspecs/features/resources.prf \
		../raspi/qt5/mkspecs/features/moc.prf \
		../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../raspi/qt5/mkspecs/features/uic.prf \
		../raspi/qt5/mkspecs/features/unix/thread.prf \
		../raspi/qt5/mkspecs/features/qmake_use.prf \
		../raspi/qt5/mkspecs/features/file_copies.prf \
		../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../raspi/qt5/mkspecs/features/exceptions.prf \
		../raspi/qt5/mkspecs/features/yacc.prf \
		../raspi/qt5/mkspecs/features/lex.prf \
		pi_controller.pro chart.h \
		rootwidget.h \
		sequence.h \
		pindefs.h \
		nanocoater.h \
		ds18b20.h main.cpp \
		chart.cpp \
		rootwidget.cpp \
		sequence.cpp \
		ds18b20.cpp
QMAKE_TARGET  = pi_controller
DESTDIR       = 
TARGET        = pi_controller


first: all
####### Build rules

$(TARGET): /home/dandi/raspi/qt5pi/lib/libQt5Charts.a /home/dandi/raspi/qt5pi/lib/libQt5Widgets.a /home/dandi/raspi/qt5pi/lib/libQt5Gui.a /home/dandi/raspi/qt5pi/lib/libQt5Core.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pi_controller.pro ../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf ../raspi/qt5/mkspecs/features/spec_pre.prf \
		../raspi/qt5/mkspecs/common/unix.conf \
		../raspi/qt5/mkspecs/common/linux.conf \
		../raspi/qt5/mkspecs/common/sanitize.conf \
		../raspi/qt5/mkspecs/common/gcc-base.conf \
		../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../raspi/qt5/mkspecs/common/g++-base.conf \
		../raspi/qt5/mkspecs/common/g++-unix.conf \
		../raspi/qt5/mkspecs/qdevice.pri \
		../raspi/qt5/mkspecs/features/device_config.prf \
		../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../raspi/qt5/mkspecs/qconfig.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_cupsprintersupport.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-brcm-integration.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-emu-integration.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-kms-integration.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qlibinputplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qminimalegl.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlite2.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qtslibplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qvnc.pri \
		../raspi/qt5/mkspecs/modules/qt_plugin_qxcb.pri \
		../raspi/qt5/mkspecs/features/qt_functions.prf \
		../raspi/qt5/mkspecs/features/qt_config.prf \
		../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../raspi/qt5/mkspecs/features/toolchain.prf \
		../raspi/qt5/mkspecs/features/default_pre.prf \
		../raspi/qt5/mkspecs/features/resolve_config.prf \
		../raspi/qt5/mkspecs/features/default_post.prf \
		../raspi/qt5/mkspecs/features/warn_on.prf \
		../raspi/qt5/mkspecs/features/qt.prf \
		../raspi/qt5/mkspecs/features/resources.prf \
		../raspi/qt5/mkspecs/features/moc.prf \
		../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../raspi/qt5/mkspecs/features/uic.prf \
		../raspi/qt5/mkspecs/features/unix/thread.prf \
		../raspi/qt5/mkspecs/features/qmake_use.prf \
		../raspi/qt5/mkspecs/features/file_copies.prf \
		../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../raspi/qt5/mkspecs/features/exceptions.prf \
		../raspi/qt5/mkspecs/features/yacc.prf \
		../raspi/qt5/mkspecs/features/lex.prf \
		pi_controller.pro \
		../raspi/qt5pi/plugins/platforms/libqeglfs.prl \
		../raspi/qt5pi/plugins/imageformats/libqgif.prl \
		../raspi/qt5pi/plugins/imageformats/libqico.prl \
		../raspi/qt5pi/plugins/imageformats/libqjpeg.prl \
		../raspi/qt5pi/plugins/egldeviceintegrations/libqeglfs-brcm-integration.prl \
		../raspi/qt5pi/plugins/egldeviceintegrations/libqeglfs-emu-integration.prl \
		../raspi/qt5pi/plugins/egldeviceintegrations/libqeglfs-kms-integration.prl \
		../raspi/qt5pi/lib/libQt5Charts.prl \
		../raspi/qt5pi/lib/libQt5Widgets.prl \
		../raspi/qt5pi/lib/libQt5Gui.prl \
		../raspi/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile pi_controller.pro
../raspi/qt5/mkspecs/features/spec_pre.prf:
../raspi/qt5/mkspecs/common/unix.conf:
../raspi/qt5/mkspecs/common/linux.conf:
../raspi/qt5/mkspecs/common/sanitize.conf:
../raspi/qt5/mkspecs/common/gcc-base.conf:
../raspi/qt5/mkspecs/common/gcc-base-unix.conf:
../raspi/qt5/mkspecs/common/g++-base.conf:
../raspi/qt5/mkspecs/common/g++-unix.conf:
../raspi/qt5/mkspecs/qdevice.pri:
../raspi/qt5/mkspecs/features/device_config.prf:
../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
../raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../raspi/qt5/mkspecs/qconfig.pri:
../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_charts.pri:
../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_core.pri:
../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_network.pri:
../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_cupsprintersupport.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-brcm-integration.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-emu-integration.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs-kms-integration.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qeglfs.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qgif.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qico.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qjpeg.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qlibinputplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qlinuxfb.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qminimalegl.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qnmbearer.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qsqlite2.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qsqltds.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qtslibplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qvnc.pri:
../raspi/qt5/mkspecs/modules/qt_plugin_qxcb.pri:
../raspi/qt5/mkspecs/features/qt_functions.prf:
../raspi/qt5/mkspecs/features/qt_config.prf:
../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf:
../raspi/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../raspi/qt5/mkspecs/features/exclusive_builds.prf:
../raspi/qt5/mkspecs/features/toolchain.prf:
../raspi/qt5/mkspecs/features/default_pre.prf:
../raspi/qt5/mkspecs/features/resolve_config.prf:
../raspi/qt5/mkspecs/features/default_post.prf:
../raspi/qt5/mkspecs/features/warn_on.prf:
../raspi/qt5/mkspecs/features/qt.prf:
../raspi/qt5/mkspecs/features/resources.prf:
../raspi/qt5/mkspecs/features/moc.prf:
../raspi/qt5/mkspecs/features/unix/opengl.prf:
../raspi/qt5/mkspecs/features/uic.prf:
../raspi/qt5/mkspecs/features/unix/thread.prf:
../raspi/qt5/mkspecs/features/qmake_use.prf:
../raspi/qt5/mkspecs/features/file_copies.prf:
../raspi/qt5/mkspecs/features/testcase_targets.prf:
../raspi/qt5/mkspecs/features/exceptions.prf:
../raspi/qt5/mkspecs/features/yacc.prf:
../raspi/qt5/mkspecs/features/lex.prf:
pi_controller.pro:
../raspi/qt5pi/plugins/platforms/libqeglfs.prl:
../raspi/qt5pi/plugins/imageformats/libqgif.prl:
../raspi/qt5pi/plugins/imageformats/libqico.prl:
../raspi/qt5pi/plugins/imageformats/libqjpeg.prl:
../raspi/qt5pi/plugins/egldeviceintegrations/libqeglfs-brcm-integration.prl:
../raspi/qt5pi/plugins/egldeviceintegrations/libqeglfs-emu-integration.prl:
../raspi/qt5pi/plugins/egldeviceintegrations/libqeglfs-kms-integration.prl:
../raspi/qt5pi/lib/libQt5Charts.prl:
../raspi/qt5pi/lib/libQt5Widgets.prl:
../raspi/qt5pi/lib/libQt5Gui.prl:
../raspi/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pi_controller.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../raspi/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents chart.h rootwidget.h sequence.h pindefs.h nanocoater.h ds18b20.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp chart.cpp rootwidget.cpp sequence.cpp ds18b20.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/dandi/pi_controller/pi_controller_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../raspi/qt5/mkspecs/features/data/dummy.cpp
	/home/dandi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/dandi/raspi/sysroot -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../raspi/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_chart.cpp moc_rootwidget.cpp moc_ds18b20.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chart.cpp moc_rootwidget.cpp moc_ds18b20.cpp
moc_chart.cpp: ../raspi/qt5pi/include/QtCharts/QChart \
		../raspi/qt5pi/include/QtCharts/qchart.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCharts/QLegend \
		../raspi/qt5pi/include/QtCharts/qlegend.h \
		../raspi/qt5pi/include/QtWidgets/QGraphicsWidget \
		../raspi/qt5pi/include/QtWidgets/qgraphicswidget.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicslayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsitem.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtCore/QTimer \
		../raspi/qt5pi/include/QtCore/qtimer.h \
		../raspi/qt5pi/include/QtCore/qbasictimer.h \
		sequence.h \
		nanocoater.h \
		pindefs.h \
		../raspi/qt5pi/include/QtCore/QPoint \
		chart.h \
		moc_predefs.h \
		../raspi/qt5/bin/moc
	/home/dandi/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/dandi/raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++ -I/home/dandi/pi_controller -I/home/dandi/raspi/qt5pi/include -I/home/dandi/raspi/qt5pi/include/QtCharts -I/home/dandi/raspi/qt5pi/include/QtWidgets -I/home/dandi/raspi/qt5pi/include/QtGui -I/home/dandi/raspi/qt5pi/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include chart.h -o moc_chart.cpp

moc_rootwidget.cpp: ../raspi/qt5pi/include/QtCharts/QChartView \
		../raspi/qt5pi/include/QtCharts/qchartview.h \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCharts/QChart \
		../raspi/qt5pi/include/QtCharts/qchart.h \
		../raspi/qt5pi/include/QtCharts/QLegend \
		../raspi/qt5pi/include/QtCharts/qlegend.h \
		../raspi/qt5pi/include/QtWidgets/QGraphicsWidget \
		../raspi/qt5pi/include/QtWidgets/qgraphicswidget.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicslayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsitem.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtWidgets/QGraphicsView \
		../raspi/qt5pi/include/QtWidgets/qgraphicsview.h \
		../raspi/qt5pi/include/QtGui/qpainter.h \
		../raspi/qt5pi/include/QtGui/qtextoption.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtWidgets/qscrollarea.h \
		../raspi/qt5pi/include/QtWidgets/qabstractscrollarea.h \
		../raspi/qt5pi/include/QtWidgets/qframe.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsscene.h \
		../raspi/qt5pi/include/QtWidgets/QHBoxLayout \
		../raspi/qt5pi/include/QtWidgets/qboxlayout.h \
		../raspi/qt5pi/include/QtWidgets/qlayout.h \
		../raspi/qt5pi/include/QtWidgets/qlayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qgridlayout.h \
		../raspi/qt5pi/include/QtWidgets/QLabel \
		../raspi/qt5pi/include/QtWidgets/qlabel.h \
		../raspi/qt5pi/include/QtWidgets/QPushButton \
		../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtWidgets/QVBoxLayout \
		../raspi/qt5pi/include/QtWidgets/QWidget \
		../raspi/qt5pi/include/QtCore/QTimer \
		../raspi/qt5pi/include/QtCore/qtimer.h \
		../raspi/qt5pi/include/QtCore/qbasictimer.h \
		chart.h \
		sequence.h \
		nanocoater.h \
		pindefs.h \
		../raspi/qt5pi/include/QtCore/QPoint \
		ds18b20.h \
		../raspi/qt5pi/include/QtCore/QThread \
		../raspi/qt5pi/include/QtCore/qthread.h \
		rootwidget.h \
		moc_predefs.h \
		../raspi/qt5/bin/moc
	/home/dandi/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/dandi/raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++ -I/home/dandi/pi_controller -I/home/dandi/raspi/qt5pi/include -I/home/dandi/raspi/qt5pi/include/QtCharts -I/home/dandi/raspi/qt5pi/include/QtWidgets -I/home/dandi/raspi/qt5pi/include/QtGui -I/home/dandi/raspi/qt5pi/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include rootwidget.h -o moc_rootwidget.cpp

moc_ds18b20.cpp: ../raspi/qt5pi/include/QtCore/QThread \
		../raspi/qt5pi/include/QtCore/qthread.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		ds18b20.h \
		moc_predefs.h \
		../raspi/qt5/bin/moc
	/home/dandi/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/dandi/raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++ -I/home/dandi/pi_controller -I/home/dandi/raspi/qt5pi/include -I/home/dandi/raspi/qt5pi/include/QtCharts -I/home/dandi/raspi/qt5pi/include/QtWidgets -I/home/dandi/raspi/qt5pi/include/QtGui -I/home/dandi/raspi/qt5pi/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ds18b20.h -o moc_ds18b20.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../raspi/qt5pi/include/QtWidgets/QMessageBox \
		../raspi/qt5pi/include/QtWidgets/qmessagebox.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../raspi/qt5pi/include/QtWidgets/qdialog.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/QApplication \
		../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../raspi/qt5pi/include/QtCore/qeventloop.h \
		../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		nanocoater.h \
		pindefs.h \
		rootwidget.h \
		../raspi/qt5pi/include/QtCharts/QChartView \
		../raspi/qt5pi/include/QtCharts/qchartview.h \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCharts/QChart \
		../raspi/qt5pi/include/QtCharts/qchart.h \
		../raspi/qt5pi/include/QtCharts/QLegend \
		../raspi/qt5pi/include/QtCharts/qlegend.h \
		../raspi/qt5pi/include/QtWidgets/QGraphicsWidget \
		../raspi/qt5pi/include/QtWidgets/qgraphicswidget.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicslayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsitem.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtWidgets/QGraphicsView \
		../raspi/qt5pi/include/QtWidgets/qgraphicsview.h \
		../raspi/qt5pi/include/QtGui/qpainter.h \
		../raspi/qt5pi/include/QtGui/qtextoption.h \
		../raspi/qt5pi/include/QtWidgets/qscrollarea.h \
		../raspi/qt5pi/include/QtWidgets/qabstractscrollarea.h \
		../raspi/qt5pi/include/QtWidgets/qframe.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsscene.h \
		../raspi/qt5pi/include/QtWidgets/QHBoxLayout \
		../raspi/qt5pi/include/QtWidgets/qboxlayout.h \
		../raspi/qt5pi/include/QtWidgets/qlayout.h \
		../raspi/qt5pi/include/QtWidgets/qlayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qgridlayout.h \
		../raspi/qt5pi/include/QtWidgets/QLabel \
		../raspi/qt5pi/include/QtWidgets/qlabel.h \
		../raspi/qt5pi/include/QtWidgets/QPushButton \
		../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		../raspi/qt5pi/include/QtWidgets/QVBoxLayout \
		../raspi/qt5pi/include/QtWidgets/QWidget \
		../raspi/qt5pi/include/QtCore/QTimer \
		../raspi/qt5pi/include/QtCore/qtimer.h \
		../raspi/qt5pi/include/QtCore/qbasictimer.h \
		chart.h \
		sequence.h \
		../raspi/qt5pi/include/QtCore/QPoint \
		ds18b20.h \
		../raspi/qt5pi/include/QtCore/QThread \
		../raspi/qt5pi/include/QtCore/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

chart.o: chart.cpp chart.h \
		../raspi/qt5pi/include/QtCharts/QChart \
		../raspi/qt5pi/include/QtCharts/qchart.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCharts/QLegend \
		../raspi/qt5pi/include/QtCharts/qlegend.h \
		../raspi/qt5pi/include/QtWidgets/QGraphicsWidget \
		../raspi/qt5pi/include/QtWidgets/qgraphicswidget.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicslayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsitem.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtCore/QTimer \
		../raspi/qt5pi/include/QtCore/qtimer.h \
		../raspi/qt5pi/include/QtCore/qbasictimer.h \
		sequence.h \
		nanocoater.h \
		pindefs.h \
		../raspi/qt5pi/include/QtCore/QPoint \
		../raspi/qt5pi/include/QtCore/QEasingCurve \
		../raspi/qt5pi/include/QtCore/qeasingcurve.h \
		../raspi/qt5pi/include/QtCharts/QCategoryAxis \
		../raspi/qt5pi/include/QtCharts/qcategoryaxis.h \
		../raspi/qt5pi/include/QtCharts/QValueAxis \
		../raspi/qt5pi/include/QtCharts/qvalueaxis.h \
		../raspi/qt5pi/include/QtCharts/QLineSeries \
		../raspi/qt5pi/include/QtCharts/qlineseries.h \
		../raspi/qt5pi/include/QtCharts/QXYSeries \
		../raspi/qt5pi/include/QtCharts/qxyseries.h \
		../raspi/qt5pi/include/QtCore/QDebug \
		../raspi/qt5pi/include/QtCore/QRandomGenerator \
		../raspi/qt5pi/include/QtCore/qrandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chart.o chart.cpp

rootwidget.o: rootwidget.cpp rootwidget.h \
		../raspi/qt5pi/include/QtCharts/QChartView \
		../raspi/qt5pi/include/QtCharts/qchartview.h \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCharts/QChart \
		../raspi/qt5pi/include/QtCharts/qchart.h \
		../raspi/qt5pi/include/QtCharts/QLegend \
		../raspi/qt5pi/include/QtCharts/qlegend.h \
		../raspi/qt5pi/include/QtWidgets/QGraphicsWidget \
		../raspi/qt5pi/include/QtWidgets/qgraphicswidget.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicslayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsitem.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtWidgets/QGraphicsView \
		../raspi/qt5pi/include/QtWidgets/qgraphicsview.h \
		../raspi/qt5pi/include/QtGui/qpainter.h \
		../raspi/qt5pi/include/QtGui/qtextoption.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtWidgets/qscrollarea.h \
		../raspi/qt5pi/include/QtWidgets/qabstractscrollarea.h \
		../raspi/qt5pi/include/QtWidgets/qframe.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtWidgets/qgraphicsscene.h \
		../raspi/qt5pi/include/QtWidgets/QHBoxLayout \
		../raspi/qt5pi/include/QtWidgets/qboxlayout.h \
		../raspi/qt5pi/include/QtWidgets/qlayout.h \
		../raspi/qt5pi/include/QtWidgets/qlayoutitem.h \
		../raspi/qt5pi/include/QtWidgets/qgridlayout.h \
		../raspi/qt5pi/include/QtWidgets/QLabel \
		../raspi/qt5pi/include/QtWidgets/qlabel.h \
		../raspi/qt5pi/include/QtWidgets/QPushButton \
		../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtWidgets/QVBoxLayout \
		../raspi/qt5pi/include/QtWidgets/QWidget \
		../raspi/qt5pi/include/QtCore/QTimer \
		../raspi/qt5pi/include/QtCore/qtimer.h \
		../raspi/qt5pi/include/QtCore/qbasictimer.h \
		chart.h \
		sequence.h \
		nanocoater.h \
		pindefs.h \
		../raspi/qt5pi/include/QtCore/QPoint \
		ds18b20.h \
		../raspi/qt5pi/include/QtCore/QThread \
		../raspi/qt5pi/include/QtCore/qthread.h \
		../raspi/qt5pi/include/QtWidgets/QApplication \
		../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../raspi/qt5pi/include/QtCore/qeventloop.h \
		../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../raspi/qt5pi/include/QtWidgets/QFileDialog \
		../raspi/qt5pi/include/QtWidgets/qfiledialog.h \
		../raspi/qt5pi/include/QtCore/qdir.h \
		../raspi/qt5pi/include/QtCore/qfileinfo.h \
		../raspi/qt5pi/include/QtWidgets/qdialog.h \
		../raspi/qt5pi/include/QtWidgets/QStyle \
		../raspi/qt5pi/include/QtWidgets/qstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rootwidget.o rootwidget.cpp

sequence.o: sequence.cpp sequence.h \
		nanocoater.h \
		pindefs.h \
		../raspi/qt5pi/include/QtCore/QPoint \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequence.o sequence.cpp

ds18b20.o: ds18b20.cpp ds18b20.h \
		../raspi/qt5pi/include/QtCore/QThread \
		../raspi/qt5pi/include/QtCore/qthread.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/QTimer \
		../raspi/qt5pi/include/QtCore/qtimer.h \
		../raspi/qt5pi/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ds18b20.o ds18b20.cpp

pi_controller_plugin_import.o: /home/dandi/pi_controller/pi_controller_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pi_controller_plugin_import.o /home/dandi/pi_controller/pi_controller_plugin_import.cpp

moc_chart.o: moc_chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chart.o moc_chart.cpp

moc_rootwidget.o: moc_rootwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rootwidget.o moc_rootwidget.cpp

moc_ds18b20.o: moc_ds18b20.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ds18b20.o moc_ds18b20.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/pi_controller/bin || mkdir -p $(INSTALL_ROOT)/opt/pi_controller/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/pi_controller/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/pi_controller/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/pi_controller/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/pi_controller/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

